Parameters:
    HostedZoneName:
        Type: String

Resources:
    CAARecords:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneName: !Ref HostedZoneName
            Type: CAA
            Name: !Ref HostedZoneName
            TTL: '1800'
            ResourceRecords:
                - '0 issue "amazon.com"'
                - '0 issue "amazontrust.com"'
                - '0 issue "awstrust.com"'
                - '0 issue "amazonaws.com"'
                - '0 issuewild "amazon.com"'
                - '0 issuewild "amazontrust.com"'
                - '0 issuewild "awstrust.com"'
                - '0 issuewild "amazonaws.com"'
